---
- name: Set access port on VLAN {{ vlan_id }}
  ansible.builtin.include_role:
    name: ansible_network.network_runner.switch
    tasks_from: conf_access_port
  vars:
    port_description: "{{ port_name }}-vlan{{ vlan_id }}"
