---
- name: Remove storage for a tenant
  hosts: localhost
  gather_facts: false

  vars:
    tenant: "{{ ansible_eda.event.payload }}"
    tenant_name: "{{ ansible_eda.event.payload.metadata.name }}"
    tenant_namespace: "{{ ansible_eda.event.payload.metadata.namespace }}"

  pre_tasks:
    - name: Show tenant
      ansible.builtin.debug:
        msg:
          - "Tenant name: {{ tenant_name }}"
          - "Tenant namespace: {{ tenant_namespace }}"

    - name: Set target cluster kubeconfig from environment
      ansible.builtin.set_fact:
        remote_cluster_kubeconfig: "{{ lookup('env', 'OSAC_REMOTE_CLUSTER_KUBECONFIG') | default('', true) }}"

  tasks:
    - name: Remove tenant StorageClasses
      ansible.builtin.include_role:
        name: osac.service.tenant_storage_provision
        tasks_from: delete
      vars:
        tenant_storage_provision_tenant_name: "{{ tenant_name }}"
        kubeconfig: "{{ remote_cluster_kubeconfig if (remote_cluster_kubeconfig | length > 0) else omit }}"
