---
current_namespace: "{{ lookup('env', 'NAMESPACE') }}"
aap_instance_name: "{{ lookup('env', 'AAP_INSTANCE_NAME', default='osac-aap') }}"
aap_hostname: "{{ lookup('env', 'AAP_HOSTNAME', default='http://' + aap_instance_name) }}"
aap_username: "{{ lookup('env', 'AAP_USERNAME', default='admin') }}"
aap_password: "{{ lookup('env', 'AAP_PASSWORD', default=Undefined) }}"
aap_validate_certs: "{{ lookup('env', 'AAP_VALIDATE_CERTS', default='true') | bool }}"
aap_organization_name: "{{ lookup('env', 'AAP_ORGANIZATION_NAME', default='osac') }}"
aap_project_name: "{{ lookup('env', 'AAP_PROJECT_NAME', default=current_namespace) }}"
aap_prefix: "{{ lookup('env', 'AAP_PREFIX', default=aap_organization_name) }}"
aap_project_git_uri: "{{ lookup('env', 'AAP_PROJECT_GIT_URI', default='https://github.com/osac-project/osac-aap.git') }}"
aap_project_git_branch: "{{ lookup('env', 'AAP_PROJECT_GIT_BRANCH', default='main') }}"
aap_project_archive_uri: "{{ lookup('env', 'AAP_PROJECT_ARCHIVE_URI', default=Undefined) }}"
aap_ee_image: "{{ lookup('env', 'AAP_EE_IMAGE', default='ghcr.io/osac-project/osac-aap:latest') }}"
license_manifest_path: "{{ lookup('env', 'LICENSE_MANIFEST_PATH', default='/var/secrets/config-as-code-manifest/license.zip') }}"
remote_cluster_kubeconfig_secret_name: "{{ lookup('env', 'REMOTE_CLUSTER_KUBECONFIG_SECRET_NAME', default='') }}"
remote_cluster_kubeconfig_secret_key: "{{ lookup('env', 'REMOTE_CLUSTER_KUBECONFIG_SECRET_KEY', default='kubeconfig') }}"
osac_publish_templates_enabled: "{{ lookup('env', 'OSAC_PUBLISH_TEMPLATES_ENABLED', default='true') | bool }}"
osac_import_agents_enabled: "{{ lookup('env', 'OSAC_IMPORT_AGENTS_ENABLED', default='false') | bool }}"
osac_import_bcm_agents_enabled: "{{ lookup('env', 'OSAC_IMPORT_BCM_AGENTS_ENABLED', default='false') | bool }}"
