---
- name: Fulfillment webhook
  hosts: localhost
  execution_strategy: parallel
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Create hosted cluster
      condition: event.meta.endpoint == "create-hosted-cluster"
      action:
        run_workflow_template:
          name: "{{ job_template_prefix }}-create-hosted-cluster-workflow"
          organization: "{{ job_template_organization }}"

    - name: Delete hosted cluster
      condition: event.meta.endpoint == "delete-hosted-cluster"
      action:
        run_workflow_template:
          name: "{{ job_template_prefix }}-delete-hosted-cluster-workflow"
          organization: "{{ job_template_organization }}"

    - name: Create compute instance
      condition: event.meta.endpoint == "create-compute-instance"
      action:
        run_job_template:
          name: "{{ job_template_prefix }}-create-compute-instance"
          organization: "{{ job_template_organization }}"

    - name: Delete compute instance
      condition: event.meta.endpoint == "delete-compute-instance"
      action:
        run_job_template:
          name: "{{ job_template_prefix }}-delete-compute-instance"
          organization: "{{ job_template_organization }}"

    - name: Create virtual network
      condition: event.meta.endpoint == "create-virtual-network"
      action:
        run_job_template:
          name: "{{ job_template_prefix }}-create-virtual-network"
          organization: "{{ job_template_organization }}"

    - name: Delete virtual network
      condition: event.meta.endpoint == "delete-virtual-network"
      action:
        run_job_template:
          name: "{{ job_template_prefix }}-delete-virtual-network"
          organization: "{{ job_template_organization }}"

    - name: Create subnet
      condition: event.meta.endpoint == "create-subnet"
      action:
        run_job_template:
          name: "{{ job_template_prefix }}-create-subnet"
          organization: "{{ job_template_organization }}"

    - name: Delete subnet
      condition: event.meta.endpoint == "delete-subnet"
      action:
        run_job_template:
          name: "{{ job_template_prefix }}-delete-subnet"
          organization: "{{ job_template_organization }}"

    - name: Create public IP
      condition: event.meta.endpoint == "create-public-ip"
      action:
        run_job_template:
          name: "{{ job_template_prefix }}-create-public-ip"
          organization: "{{ job_template_organization }}"

    - name: Delete public IP
      condition: event.meta.endpoint == "delete-public-ip"
      action:
        run_job_template:
          name: "{{ job_template_prefix }}-delete-public-ip"
          organization: "{{ job_template_organization }}"

    - name: Attach public IP
      condition: event.meta.endpoint == "attach-public-ip"
      action:
        run_job_template:
          name: "{{ job_template_prefix }}-attach-public-ip"
          organization: "{{ job_template_organization }}"

    - name: Detach public IP
      condition: event.meta.endpoint == "detach-public-ip"
      action:
        run_job_template:
          name: "{{ job_template_prefix }}-detach-public-ip"
          organization: "{{ job_template_organization }}"

    - name: Create public IP pool
      condition: event.meta.endpoint == "create-public-ip-pool"
      action:
        run_job_template:
          name: "{{ job_template_prefix }}-create-public-ip-pool"
          organization: "{{ job_template_organization }}"

    - name: Delete public IP pool
      condition: event.meta.endpoint == "delete-public-ip-pool"
      action:
        run_job_template:
          name: "{{ job_template_prefix }}-delete-public-ip-pool"
          organization: "{{ job_template_organization }}"

    - name: Create org storage
      condition: event.meta.endpoint == "create-org"
      action:
        run_job_template:
          name: "{{ job_template_prefix }}-create-org"
          organization: "{{ job_template_organization }}"

    - name: Delete org storage
      condition: event.meta.endpoint == "delete-org"
      action:
        run_job_template:
          name: "{{ job_template_prefix }}-delete-org"
          organization: "{{ job_template_organization }}"
