aap:
  instance:
    enabled: true
    name: "osac-aap"
    controller:
      disabled: false
    eda:
      disabled: false
    hub:
      disabled: true
    lightspeed:
      disabled: true
    redisMode: standalone
    routeTlsTerminationMechanism: Edge
    imagePullPolicy: IfNotPresent

bootstrap:
  enabled: true
  image: ghcr.io/osac-project/osac-aap:latest
  cliImage: quay.io/openshift/origin-cli:4.20.0
  backoffLimit: 15

configAsCode:
  manifestSecret: "config-as-code-manifest-ig"
  secret: "config-as-code-ig"

serviceAccounts:
  osacSa: "osac-sa"
  templatePublisher: "template-publisher"
